### ISSUE TITLE
fix the arrow bug

### ISSUE THREAD

**Issue by Blankwonder** [rob-brown/RBFilePreviewer#1]
You can add this code to bring the arrow back. But this hack may cause other problems when other uses your subclass.

``` objective-c
- (Class)class {
    return [QLPreviewController class];
}
```

**Comment by Blankwonder** [comment]
this code may be better

``` objective-c
- (Class)class {
    if (_loadFinished)
        return [super class];
    else
        return [QLPreviewController class];
}
```

**Comment by rob-brown** [comment]
Thanks for the fix. I don't expect this hack to cause too many other problems. I don't know of a good need for anyone outside of the OS to ask for the Class of a view controller.
