### ISSUE TITLE
How to hide this action button

### ISSUE THREAD

**Issue by vinhhoangdo** [rob-brown/RBFilePreviewer#8]
I don't want that the user can share this document with others so please let me know how to hide this button.

![image](https://user-images.githubusercontent.com/69976122/195757721-ab4f958c-15ea-4ea2-b31f-e528ffacd5e9.png)

**Comment by rob-brown** [comment]
I'm not sure hiding that button is possible. This code hasn't worked since iOS 5 anyway.
